# Generated by Django 2.0.7 on 2018-07-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchbox',
            old_name='title',
            new_name='search',
        ),
    ]
