# Generated by Django 2.0.7 on 2018-08-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0002_auto_20180728_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('searchQuerry', models.CharField(max_length=100)),
                ('reviewText', models.TextField()),
            ],
        ),
    ]
